# Generated by Django 3.1.4 on 2020-12-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20201217_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task1',
        ),
    ]
