# Generated by Django 3.1.4 on 2020-12-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_task1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='task1',
            old_name='created',
            new_name='heading',
        ),
    ]
