# Generated by Django 3.1.4 on 2020-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20201217_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='heading',
            new_name='bold',
        ),
        migrations.RenameField(
            model_name='task1',
            old_name='heading',
            new_name='bold',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='heading1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='heading2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='heading3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='heading4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='heading5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='underline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task1',
            name='heading1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task1',
            name='heading2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task1',
            name='heading3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task1',
            name='heading4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task1',
            name='heading5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task1',
            name='italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task1',
            name='underline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='task1',
            name='title',
            field=models.CharField(max_length=1000000),
        ),
    ]
