# Generated by Django 3.1.4 on 2020-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_auto_20201217_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task1',
            name='title',
            field=models.TextField(),
        ),
    ]
