# Generated by Django 3.1.4 on 2020-12-18 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20201218_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task1',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
