# Generated by Django 3.1.4 on 2020-12-18 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_auto_20201218_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='bold',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='task1',
            old_name='bold',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='task',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='heading3',
        ),
        migrations.RemoveField(
            model_name='task',
            name='heading4',
        ),
        migrations.RemoveField(
            model_name='task',
            name='heading5',
        ),
        migrations.RemoveField(
            model_name='task',
            name='italic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='underline',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='heading3',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='heading4',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='heading5',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='italic',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='underline',
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
