# Generated by Django 3.1.4 on 2020-12-18 16:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_auto_20201218_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task1',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
