# Generated by Django 3.1.4 on 2020-12-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='names',
        ),
    ]
